In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df= pd.read_excel("Iris.xlsx")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [24]:
q=df.drop("Id",axis=1)

In [26]:
q

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [28]:
X=df.drop(["Species"],axis=1)
y=df["Species"]

In [30]:
X

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [32]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [34]:
from sklearn.preprocessing import MinMaxScaler
scalar= MinMaxScaler()
X_scaled = scalar.fit_transform(X)
X_scaled

array([[0.        , 0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.00671141, 0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.01342282, 0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.02013423, 0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.02684564, 0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.03355705, 0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.04026846, 0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.04697987, 0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.05369128, 0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.06040268, 0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.06711409, 0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.0738255 , 0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.08053691, 0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.08724832, 0.        , 0.41666667, 0.01694915, 0.        ],
       [0.09395973, 0.41666667, 0.

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,y , test_size=0.2, random_state=43)

In [44]:
from sklearn.naive_bayes import GaussianNB

In [50]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB()

In [54]:
y_pred= gnb.predict(X_test)

In [56]:
y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

In [58]:
y_test

30         Iris-setosa
0          Iris-setosa
138     Iris-virginica
67     Iris-versicolor
105     Iris-virginica
39         Iris-setosa
113     Iris-virginica
71     Iris-versicolor
81     Iris-versicolor
57     Iris-versicolor
38         Iris-setosa
76     Iris-versicolor
122     Iris-virginica
11         Iris-setosa
78     Iris-versicolor
97     Iris-versicolor
15         Iris-setosa
12         Iris-setosa
114     Iris-virginica
100     Iris-virginica
37         Iris-setosa
45         Iris-setosa
1          Iris-setosa
134     Iris-virginica
126     Iris-virginica
118     Iris-virginica
17         Iris-setosa
88     Iris-versicolor
2          Iris-setosa
10         Iris-setosa
Name: Species, dtype: object

In [68]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [78]:
# Testing Model Evaluation

y_pred = gnb.predict(X_test)

cnf_matrix = confusion_matrix(y_pred, y_test)
print("Confusion Matrix:\n",cnf_matrix)
print("-"*60)

accuracy = accuracy_score(y_pred, y_test)
print("Accuracy:",accuracy)
print("-"*60)

clf_report = classification_report(y_pred, y_test)
print("Classification Report:\n",clf_report)

Confusion Matrix:
 [[13  0  0]
 [ 0  8  0]
 [ 0  0  9]]
------------------------------------------------------------
Accuracy: 1.0
------------------------------------------------------------
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      1.00      1.00         8
 Iris-virginica       1.00      1.00      1.00         9

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [90]:
# Training Model Evaluation

y_pred_train = gnb.predict(X_train)

cnf_matrix = confusion_matrix(y_pred_train, y_train)
print("Confusion Matrix:\n",cnf_matrix)
print("-"*60)

accuracy = accuracy_score(y_pred_train, y_train)
print("Accuracy:",accuracy)
print("-"*60)

clf_report = classification_report(y_pred_train, y_train)
print("Classification Report:\n",clf_report)

Confusion Matrix:
 [[37  0  0]
 [ 0 42  1]
 [ 0  0 40]]
------------------------------------------------------------
Accuracy: 0.9916666666666667
------------------------------------------------------------
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        37
Iris-versicolor       1.00      0.98      0.99        43
 Iris-virginica       0.98      1.00      0.99        40

       accuracy                           0.99       120
      macro avg       0.99      0.99      0.99       120
   weighted avg       0.99      0.99      0.99       120



In [94]:
gnb.score(X_train,y_train)

0.9916666666666667

In [96]:
gnb.score(X_test,y_test)

1.0